//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoBlogApp.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoProject
    {
        public int PhotoProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public int Order { get; set; }
        public Nullable<int> RequestId { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
