//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoBlogApp.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.PhotoProjects = new HashSet<PhotoProject>();
        }
    
        public int RequestId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Comment { get; set; }
        public string ContactInfo { get; set; }
    
        public virtual ICollection<PhotoProject> PhotoProjects { get; set; }
    }
}
